# Generated by Django 5.2.1 on 2025-06-04 02:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_picture',
            field=models.ImageField(blank=True, null=True, upload_to='banner_pictures'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10, message='El texto debe tener al menos 10 caracteres'), django.core.validators.MaxLengthValidator(500, message='El texto debe tener menos de 500 caracteres')]),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^https://www\\.facebook\\.com/[^/]+$', message='El enlace debe ser un enlace válido de Facebook')]),
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^https://instagram\\.com/[^/]+$', message='El enlace debe ser un enlace válido de Instagram')]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{10,15}$', message='El número debe tener entre 10 y 15 dígitos')]),
        ),
        migrations.AddField(
            model_name='user',
            name='pinterest',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^https://pinterest\\.com/[^/]+$', message='El enlace debe ser un enlace válido de Pinterest')]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^https://twitter\\.com/[^/]+$', message='El enlace debe ser un enlace válido de Twitter')]),
        ),
    ]
